name: Deploy with Docker Compose
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted

    env:
      PROJECT_PATH: ${{ secrets.PROJECT_PATH }}

    steps:
        -   name: Deploy app
            run: |
                cd "$PROJECT_PATH"
                docker compose pull app
                docker compose up -d app
